name: gh-lab-ci

on:
  push:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}



jobs:

  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Print Commit ID
          run: 
            CI_DATE=$(date +%s);
            CI_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7);
            echo $CI_DATE
            echo $CI_SHA_SHORT

        - name: Declare sha short and branch
          shell: bash
          run: |
            echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
            echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        
        - name: Print the variables
          run: |
            echo "Branch: ${{ env.branch }}"
            echo "Sha: ${{ env.sha_short }}"

        

