name: gh-lab-ci

on:
  push:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}



jobs:

  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
    
        - name: Env Collection
          run : |
            BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
            GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)
            echo $BRANCH_NAME
            echo $GITHUB_SHA_SHORT
            echo "GITHUB_SHA is $GITHUB_SHA"
            echo "CI_DATE=$(date +%s)" >> "$GITHUB_ENV";
            echo "CI_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
            echo ${{ env.CI_DATE}}
            echo ${{ env.CI_SHA_SHORT}}
            echo "CI_SHA_SHORT=${GITHUB_SHA:0:7}"

        - name: Set env for image tag
          run: |
            echo "CI_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV;
            echo "CI_IMAGE_TAG=${{ github.ref }}" >> $GITHUB_ENV;
            echo "CI_COMMIT_TAG=${{ github.ref }}" >> $GITHUB_ENV
            echo "CI_COMMIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "CI_COMMIT_REF_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
            ${{ env.CI_SHA_SHORT }}
            ${{ env.CI_IMAGE_TAG }}
            ${{ env.CI_COMMIT_TAG }}
            ${{ env.CI_COMMIT_BRANCH }}
            ${{ env.CI_COMMIT_REF_NAME }}


        - name: Runner Path Collection
          run : |
            echo ${{ github.workspace }}
            cd ${{ github.workspace }}
            ls

        

