name: gh-lab-ci

on:
  push:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}



jobs:

  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Print Commit ID
          run: 
            CI_DATE=$(date +%s);
            CI_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7);
            echo $CI_DATE
            echo $CI_SHA_SHORT

        - name: Print URL
          run:
            URL="oh-inscription-worker:${{ env.CI_SHA_SHORT }}-${{ env.CI_DATE }}"
            echo $URL

        

