name: gh-lab-ci

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /
  release:
    types: [published, created, released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set env for image tag
        run: |
          echo "CI_IMAGE_TAG=$(echo ${{ github.ref }} | tr '/' '-')" >> $GITHUB_ENV
          echo "CI_COMMIT_TAG=${{ github.event.release.name }}" >> $GITHUB_ENV
          echo "CI_COMMIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "CI_COMMIT_REF_NAME=$(echo ${{ github.ref }} | tr '/' '-')" >> $GITHUB_ENV
          echo "CI_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV
  
      - name: Print variable values
        run: |
          echo "CI_IMAGE_TAG: $CI_IMAGE_TAG"
          echo "CI_COMMIT_TAG: $CI_COMMIT_TAG"
          echo "CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH"
          echo "CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME"
          echo "CI_SHA_SHORT: $CI_SHA_SHORT"

      - name: Runner Path Collection
        run : |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}
          ls
