name: gh-lab-ci

on:
  push:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}



jobs:

  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
    
        - name: Env Collection
          run : |
            BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
            GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
            echo $BRANCH_NAME
            echo $GITHUB_SHA_SHORT
            echo "GITHUB_SHA is $GITHUB_SHA"


        - name: Runner Path Collection
          run : |
            echo ${{ github.workspace }}
            cd ${{ github.workspace }}
            ls

        

