name: gh-lab-ci

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     types: [ opened, synchronize ]
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /
  release:
    types: [published, created, released]
  workflow_dispatch:



jobs:

  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
    
        - name: Env Collection
          run : |
            BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
            GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)
            echo $BRANCH_NAME
            echo $GITHUB_SHA_SHORT
            echo "GITHUB_SHA is $GITHUB_SHA"
            echo "CI_DATE=$(date +%s)" >> "$GITHUB_ENV";
            echo "CI_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
            echo ${{ env.CI_DATE}}
            echo ${{ env.CI_SHA_SHORT}}
            echo "CI_SHA_SHORT=${GITHUB_SHA:0:7}"


        - name: Set env for image tag
          run: |
            echo "CI_IMAGE_TAG=$(echo ${{ github.ref}} | tr '/' '-')" >> $GITHUB_ENV;
            echo "CI_COMMIT_TAG=${{ github.event.release.name }}" >> $GITHUB_ENV;
            echo "CI_COMMIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV;
            echo "CI_COMMIT_REF_NAME=$(echo ${{ github.ref_name }} | tr '/' '-')" >> $GITHUB_ENV
            echo "CI_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV;
            echo $CI_SHA_SHORT
            echo $CI_IMAGE_TAG
            echo $CI_COMMIT_TAG
            echo $CI_COMMIT_BRANCH
            echo $CI_COMMIT_REF_NAME


        - name: Runner Path Collection
          run : |
            echo ${{ github.workspace }}
            cd ${{ github.workspace }}
            ls

        

