name: Reusable Job Templates

on:
    push

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:20.10.23-dind
                env:
                    PROJECT_NAME: "app"
                options: --tls=false
                    
        steps:
            - uses: actions/checkout@v3

            # Runs a single command using the runners shell
            - name: schema-test
              run: |
                apt install tree
                tree
                
    on-mr:
        runs-on: ubuntu-latest
        rules:
            - if: "$CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH"
              when: on_success
        
    on-default-branch:
        runs-on: ubuntu-latest
        rules:
            - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
              when: on_success
        
    on-tag:
        runs-on: ubuntu-latest
        rules:
            - if: "$CI_COMMIT_TAG"
              when: on_success
