name: Postgres Workflow

on:
  push:
    branches:
      - main

jobs:
  postgres-setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    env:
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Docker container IP
        id: docker
        run: |
          ip=$(docker ps -q | xargs -n 1 docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' | cut -d' ' -f1)
          echo "ip=$ip" >> $GITHUB_ENV

      - name: Print Docker container IP
        run: echo "The IP address of the PostgreSQL service is ${{ env.ip }}"

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # Create table
      - name: Create table
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}  
        run: |
          psql -h ${{ env.ip }} -p ${{ env.POSTGRES_PORT }} -U ${{ env.POSTGRES_USER }} -d luxor_index -c "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL);"
      
      # Insert data  
      - name: Insert data
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          psql -h ${{ env.ip }} -p ${{ env.POSTGRES_PORT }} -U ${{ env.POSTGRES_USER }} -d luxor_index -c "INSERT INTO users (name) VALUES ('John'), ('Jane'), ('Mary');"
      
      # Query data
      - name: Query data
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          psql -h ${{ env.ip }} -p ${{ env.POSTGRES_PORT }} -U ${{ env.POSTGRES_USER }} -d luxor_index -c "SELECT * FROM users;"
            

