name: Release Workflow

on:
  push:
    tags:
      - '*' # Push events to every tag not containing / 
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set env for image tag
        run: |
          TAG_NAME=$(basename ${{ github.ref }})
          echo "CI_IMAGE_TAG=${TAG_NAME}" >> $GITHUB_ENV
          echo "CI_COMMIT_TAG=${TAG_NAME}" >> $GITHUB_ENV
          echo "CI_COMMIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "CI_COMMIT_REF_NAME=$(echo ${{ github.ref }} | tr '/' '-')" >> $GITHUB_ENV
          echo "CI_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Print variable values
        run: |
          echo "CI_IMAGE_TAG: ${{ env.CI_IMAGE_TAG }}"
          echo "CI_COMMIT_TAG: ${{ env.CI_COMMIT_TAG }}"
          echo "CI_COMMIT_BRANCH: ${{ env.CI_COMMIT_BRANCH }}"
          echo "CI_COMMIT_REF_NAME: ${{ env.CI_COMMIT_REF_NAME }}"
          echo "CI_SHA_SHORT: ${{ env.CI_SHA_SHORT }}"

      - name: Get Branch
        run: |
          RAW=$(git branch -r --contains ${{ github.ref }})
          echo "BRANCH=${RAW/origin\/}" >> $GITHUB_ENV
          echo "${{ env.BRANCH }}"

      # - name: Run Makefile
      #   run: make print-env

